1). Concatenate two lists index-wise
list1 = ["M", "na", "i", "Ke"]
list2 = ["y", "me", "s", "lly"]
Answer = ['My', 'name', 'is', 'Kelly']

In [ ]:
list1 = ["M", "na", "i", "Ke"]
list2 = ["y", "me", "s", "lly"]
list3 = [i+j for i,j in zip(list1,list2)]
print(list3)
print(tuple(zip(list1,list2)))

['My', 'name', 'is', 'Kelly']
(('M', 'y'), ('na', 'me'), ('i', 's'), ('Ke', 'lly'))

Given a Python list. Turn every item of a list into its square
List1 = [1, 2, 3, 4, 5, 6, 7]
Answer = [1, 4, 9, 16, 25, 36, 49]

In [ ]:
List1 = [1,2,3,4,5,6,7]
Answer = [1, 4, 9, 16, 25, 36, 49]
answer = [n*n for n in List1]
print(answer)

[1, 4, 9, 16, 25, 36, 49]

Given a two Python list. Iterate both lists simultaneously such that list1 should display item in
original order and list2 in reverse order
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
Answer = 10 400
20 300
30 200
40 100

In [ ]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
list3 = list2[::-1]
print(list3)
print(tuple(zip(list1,list3)))

[400, 300, 200, 100]
((10, 400), (20, 300), (30, 200), (40, 100))

In [3]:
List1 = [1,2,3,4,5,6,7]
Answer = [1, 4, 9, 16, 25, 36, 49]
answer = [i*i for i in List1]
print(answer)

[1, 4, 9, 16, 25, 36, 49]

In [9]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
list2 = list2[::-1]
print(list2)
for i, j in zip(list1,list2):
  print(i,j)

[400, 300, 200, 100]
10 400
20 300
30 200
40 100

list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
Sub List to be added = ["h", "i", "j"]
Answer = ['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

In [13]:
list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
sub_list = ["h", "i", "j"]
Answer = ['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

list1[2][1][2].extend(sub_list)  #to adding elements to list use extend
print(list1)

['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

5). Given a Python list, remove all occurrence of 20 from the list
list1 = [5, 20, 15, 20, 25, 50, 20]
Answer = [5, 15, 25, 50]

In [16]:
list1 = [5, 20, 15, 20, 25, 50, 20]
Answer = [5, 15, 25, 50]

for x in list1:
  if x == 20:
    list1.remove(x)
print(list1)

[5, 15, 25, 50]

In [22]:
#Below are the two lists convert it into the dictionary
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
Answer = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}

dic1 = dict(zip(keys,values))
print(dic1)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

In [37]:
#Merge following two Python dictionaries into one
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

Answer = {'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}


#method 1
dict3 = {**dict1, **dict2}
print(dict3)


#method 2
def Merge(dict1, dict2):
    return(dict1.update(dict2))


# Driver code
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

# This returns None
print(Merge(dict1, dict2))

# changes made in dict2
print(dict1)

#method 3
x = dict1 | dict2
print(x)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
None
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

Rename key city to location in the following dictionary
sampleDict = {
"name": "Kelly",
"age":25,
"salary": 8000,
"city": "New york"
}
Answer = {
"name": "Kelly",
"age":25,
"salary": 8000,
"location": "New york"
}

In [48]:
sampleDict = {
"name": "Kelly",
"age":25,
"salary": 8000,
"city": "New york"
}

print(sampleDict)

Answer = {
"name": "Kelly",
"age":25,
"salary": 8000,
"location": "New york"
}

sampleDict["location"] = sampleDict.pop("city")  #can remove keys using pop() method
#remove and assign same thing happens together
print(sampleDict)

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'city': 'New york'}
{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'New york'}

#Delete set of keys from Python Dictionary

sampleDict = {
"name": "Kelly",
"age":25,
"salary": 8000,
"city": "New york"
}
keysToRemove = ["name", "salary"]
Answer = {'city': 'New york', 'age': 25}

In [54]:
sampleDict = {
"name": "Kelly",
"age":25,
"salary": 8000,
"city": "New york"
}

keysToRemove = ["name", "salary"]

Answer = {'city': 'New york', 'age': 25}

#method 1

for i in keysToRemove:
  sampleDict.pop(i)
print(sampleDict)

#method 1
sampleDict.pop("name")
sampleDict.pop("salary")

print(sampleDict)

{'age': 25, 'city': 'New york'}

Create a new dictionary by extracting the following keys from a given dictionary
Given Dictionary
sampleDict = {
"name": "Kelly",
"age":25,
"salary": 8000,
"city": "New york"
}
Keys to extract
keys = ["name", "salary"]
Answer = {'name': 'Kelly', 'salary': 8000}

In [65]:
#Given Dictionary
sampleDict = {
"name": "Kelly",
"age":25,
"salary": 8000,
"city": "New york"
}

#Keys to extract
keys = ["name", "salary"]
Answer = {'name': 'Kelly', 'salary': 8000}

answer = dict()
for i in sampleDict.keys() and keys:
  answer[i] = sampleDict[i]
print(answer)

{'name': 'Kelly', 'salary': 8000}

Given a list iterate it and display numbers which are divisible by 5 and if you find number
greater than 150 stop the loop iteration
list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
Answer =
15
55
75
150

In [70]:
list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]

for i in list1:
  if i > 150:
    break
  if (i % 5) == 0:
    print(i)

15
55
75
150

Generate a Python list of all the even numbers between 4 to 30

Answer = [4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [77]:
list = []

for x in range (4,30):
  if (x %2 ) == 0:
    list.append(x)
print(list)

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

Count all lower case, upper case, digits, and special symbols from a given string
input_str = "P@#yn26at^&i5ve"
Total counts of chars, digits,and symbols
Chars = 8
Digits = 3
Symbol = 4

In [81]:
input_str = "P@#yn26at^&i5ve"

lcount=0;
upcount=0;
digcount=0;
symbol=0;

for char in input_str:
  if char.islower():
    lcount+=1
  elif char.isupper():
    upcount+=1
  elif char.isdigit():
    digcount+=1
  else:
    symbol+=1

print("lower count: ",lcount,"uppercase count: ",upcount,"digit count",digcount,"symbols count:",symbol)

lower count:  7 uppercase count:  1 digit count 3 symbols count: 4

Given an input string, count occurrences of all characters within a string
count("pynativepynvepynative") = {'p': 3, 'y': 3, 'n': 3, 'a': 2, 't': 2, 'i': 2,
'v': 3, 'e': 3}

In [87]:
input_str = "pynativepynvepynative"
answer = {'p': 3, 'y': 3, 'n': 3, 'a': 2, 't': 2, 'i': 2,'v': 3, 'e': 3}

newDict = dict()
for char in input_str:
  count = input_str.count(char)
  newDict[char]=count

print(newDict)

{'p': 3, 'y': 3, 'n': 3, 'a': 2, 't': 2, 'i': 2, 'v': 3, 'e': 3}

In [94]:
import random

dice=[1,2,3,4,5,6]
for i in range(5):
  print(random.choice(dice))
print("")

#to get same outpput number
dice=[1,2,3,4,5,6]
for i in range(5):
  random.seed(34)
  print(random.choice(range(1,6)))

1
6
5
4
5

5
5
5
5
5